"""Export the Operator admin OpenAPI contract for frontend type generation."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from fastapi import FastAPI

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPOSITORY_ROOT / "src"))

from agent_memory_service.auth import TokenService  # noqa: E402
from agent_memory_service.control import ControlModule, InMemoryControlStore  # noqa: E402
from agent_memory_service.http import create_http_app  # noqa: E402
from agent_memory_service.memory import MemoryModule  # noqa: E402
from agent_memory_service.stores.memory import InMemoryTenantMemoryRouter  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    schema = _admin_openapi_schema(_app())
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(_typescript_module(schema), encoding="utf-8")


def _app() -> FastAPI:
    store = InMemoryControlStore()
    tokens = TokenService(store)
    control = ControlModule(store, tokens)
    memory = MemoryModule(InMemoryTenantMemoryRouter([]))
    return create_http_app(memory, tokens, control=control)


def _admin_openapi_schema(app: FastAPI) -> dict[str, object]:
    schema = app.openapi()
    schema["paths"] = {
        path: operations
        for path, operations in schema.get("paths", {}).items()
        if path.startswith("/api/v1/admin/")
    }
    _prune_components(schema)
    return schema


def _prune_components(schema: dict[str, object]) -> None:
    components = schema.get("components")
    if not isinstance(components, dict):
        return
    schemas = components.get("schemas")
    if not isinstance(schemas, dict):
        return

    reachable = _referenced_component_names(schema.get("paths", {}))
    queue = list(reachable)
    while queue:
        name = queue.pop()
        component = schemas.get(name)
        if component is None:
            continue
        for nested in _referenced_component_names(component):
            if nested not in reachable:
                reachable.add(nested)
                queue.append(nested)
    components["schemas"] = {
        name: component for name, component in schemas.items() if name in reachable
    }


def _referenced_component_names(value: object) -> set[str]:
    names: set[str] = set()
    if isinstance(value, dict):
        ref = value.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/components/schemas/"):
            names.add(ref.removeprefix("#/components/schemas/"))
        for nested in value.values():
            names.update(_referenced_component_names(nested))
    elif isinstance(value, list):
        for item in value:
            names.update(_referenced_component_names(item))
    return names


def _typescript_module(schema: dict[str, object]) -> str:
    document = json.dumps(schema, indent=2, sort_keys=True)
    return (
        "/* Generated by scripts/export-admin-openapi.py. */\n"
        "/* eslint-disable */\n"
        f"export const adminOpenApi = {document} as const;\n\n"
        "export type AdminOpenApi = typeof adminOpenApi;\n"
    )


if __name__ == "__main__":
    main()
